# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 388b41bc031aff1ecb19525c546188b028a231491b6cf460e3f271563edd3d1b480ffc611217ad27b640be5a2f928ed0a3e8d8b0c9a2d5082c12a9309a7c1cac

test:
  secret_key_base: 7cf5ecdd26db636598f5e8123fa7bf5a164aeecac2d2eaacc2b37e543ecc7a301139c88534f3e3034dcaad4e8b609b791ee8e329e8ff36259b9336939111d166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
